### ISSUE TITLE
Replace Image assets with appropriate alternatives.

### ISSUE THREAD

**Issue by obeid** [dsausa/DSA-Chapter-Starter-Theme#1]
The theme needs images to convey themes of solidarity, self-organization and other socialist ideals. Please utilize appropriately licensed images. I could use some guidance as to what license could that be.

**Comment by nmashton** [comment]
I can help with this.

As a baseline, we can add some images of DSAers rallying etc. I've found some good ones (one off WP, two off the DSA site); I haven't checked the licenses, but I assume WP is okay and the others are "it's from the DSA site, so if anyone complains, I'll roll my eyes at Maria and/or David until they cut it out"-licensed.

I've also got a good version of the DSA logo. I'm concerned about how it looks on small scales, though.

**Comment by obeid** [comment]
Have a look at Flickr Commons for more generic background-ish images. https://www.flickr.com/commons
