### ISSUE TITLE
Replace or remove "projects" 

### ISSUE THREAD

**Issue by nmashton** [dsausa/DSA-Chapter-Starter-Theme#18]
We should anticipate the needs of DSA branches a little better than the theme currently does. It includes "Posts" and "Projects". The former is useful, since branches often have blogs. The latter is not particularly meaningful in this context. Either we should remove Projects or we should re-engineer it to be more useful for the branches.

If we want to rework Projects, perhaps a more appropriate replacement would be "campaigns". Often organizations run discrete campaigns with a beginning and an end, and it would be useful to have a place to post info about those. That's kinda project-like.

That said, _removing Projects is probably just fine_ for now. It's unclear to me what Projects is supposed to be besides an advertisement for the theme creator's other work, and maybe we're better off just ditching it for now.

However, if that's the road we go down, we should **document how to add new site sections** so that we know how to plug something more useful into the place where Projects currently is. (We might want a section for a photo gallery, for example.)

**Comment by obeid** [comment]
For now, I feel like we can utilize these as static links to other socialist website that we want to drive traffic to. Publications, associations, unions and whatnot.

There's a lot of cutesy UI things happening, I will try to kill these as soon as possible.

**Comment by nmashton** [comment]
Fixed by #21.
