### ISSUE TITLE
Enhance the README

### ISSUE THREAD

**Issue by obeid** [dsausa/DSA-Chapter-Starter-Theme#5]
There should be a clearer statement of the intent of this repo, a getting started guide, maybe a list of already deployed websites.

**Comment by voidestructor** [comment]
I am working on this.

**Comment by voidestructor** [comment]
fixed. check please here : https://github.com/voidestructor/DSA-Chapter-Starter-Theme/commit/22674d3a8aa50724dbb20e72c0ac2869c2732e6a

**Comment by obeid** [comment]
Thanks @voidestructor
