### ISSUE TITLE
Suggest a simpler theme to base this on

### ISSUE THREAD

**Issue by obeid** [dsausa/DSA-Chapter-Starter-Theme#6]

**Comment by nmashton** [comment]
Are we in too deep now to replace it?

Also, are we using Halve because that's what I originally forked? Yeah … I just thought it looked nice. :) But maybe simpler would've been better.

**Comment by obeid** [comment]
The goal I think is to bare down this somehow complex theme. I know it might sound counterproductive but starting with a somehow problematic theme might be more helpful; We start removing unnecessary stuff as we get more familiar with the codebase vs. starting with a simple/ nice theme and add things as we go potentially increasing the complexity of a once simple theme.

Basically with the complex-first approach, the work is laid out and we know what to remove to get it to where we want it. With the simple first, we might waste time theorizing about what we need to add and potentially end up with the wrong solution to a solved problem.

I think our biggest gain right now is familiarity with the Jekyll and github pages ecosystem.

But yeah, this is highly experimental repo and If we focus on not coupling components tightly, I don't think we will ever be too deep to make a radical change.

**Comment by obeid** [comment]
But yeah let's close this for the time being.
